### ISSUE TITLE
Update for netCore 3

### ISSUE THREAD

**Issue by paulovila** [ValeraT1982/AOP#2]
Hi, would it be possible to update the sources to newtcore3? In particular would it be possible to create a DispatcherProxy of a class as opposed to an interface?
Regards

**Comment by ValeraT1982** [comment]
Hi @paulovila. Didn't look at it for a long time. What was changed in netCore 3 that can affect this example?

**Comment by paulovila** [comment]
> Hi @paulovila. Didn't look at it for a long time. What was changed in netCore 3 that can affect this example?

Quite a few, how to instantiate the proxy, and apparently you need to implement an interface?

Ju

**Comment by ValeraT1982** [comment]
@paulovila do you know how to do it? You can create a pull request and I'll have a look

**Comment by paulovila** [comment]
The DispatchProxy is a totally different concept which doesn't equate to RealProxy. In fact, DispatchProxy is equivalent to having your own implementation of the ICalculator interface within your own logging, for which  the DispatchProxy is not necessary. The fact that it forces to define an interface defeats the purpose of the proxy.
In a real case scenario, I can't see how  DispatchProxy is solving the problem that RealProxy did.
